### ISSUE TITLE
Really 💗 the animated GIF in your readme!

### ISSUE THREAD

**Issue by PySimpleGUI** [herbzhao/steam_shortcut_editor#1]
It's unusual for Python programs to have a GUI.... it's rare that the programmer adds a screenshot to their readme.... so it was a **_thrill_** to run across your repo and see the GIF in your readme!  Very nicely done!

**Comment by mysteriousHerb** [comment]
Thank you so much for the comment. It is a very easy-to-use library and definitely made it possible to create an app with GUI within a day! (I had more trouble getting Tkinter installed on the deck than coding this up)
